### ISSUE TITLE
Exceptions thrown during use (Listed below when found)

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-4.70#65]
In KryptonDataGridView.cs line 1153 state = normal
image
![image](https://user-images.githubusercontent.com/2418812/43634852-4d3922a8-9705-11e8-93d7-79069290376a.png)

**Comment by Smurf-IV** [comment]
In `AccurateText.cs` line 305
`Color tmpColor = tmpBrush?.Color ?? SystemColors.ActiveCaptionText;`

**Comment by Smurf-IV** [comment]
TrackBarController:
```

System.NullReferenceException: Object reference not set to an instance of an object.
   at ComponentFactory.Krypton.Toolkit.TrackBarController.MouseMove(Control c, Point pt)
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseMove(Point pt)
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseMove(Point pt)
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseMove(Point pt)
   at ComponentFactory.Krypton.Toolkit.ViewBase.MouseMove(Point pt)
   at ComponentFactory.Krypton.Toolkit.ViewManager.MouseMove(MouseEventArgs e, Point rawPt)
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at ComponentFactory.Krypton.Toolkit.VisualControlBase.WndProc(Message& m)
   at ComponentFactory.Krypton.Toolkit.KryptonTrackBar.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) 

```

**Comment by Smurf-IV** [comment]
Toolkit.VisualPanel.PaintTransparentBackground:
```

System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
   at ComponentFactory.Krypton.Toolkit.VisualPanel.PaintTransparentBackground(PaintEventArgs e) in Z:\Build the External Components\Krypton-NET-4.7\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualPanel.cs:line 1035
   at ComponentFactory.Krypton.Toolkit.VisualPanel.OnPaint(PaintEventArgs e) in Z:\Build the External Components\Krypton-NET-4.7\Krypton Components\ComponentFactory.Krypton.Toolkit\Controls Visuals\VisualPanel.cs:line 799
   at System.Windows.Forms.Control.PaintTransparentBackground(PaintEventArgs e, Rectangle rectangle, Region transparentRegion)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.ScrollableControl.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintTransparentBackground(PaintEventArgs e, Rectangle rectangle, Region transparentRegion)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.ScrollableControl.OnPaintBackground(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintTransparentBackground(PaintEventArgs e, Rectangle rectangle, Region transparentRegion)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)
   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle)
   at System.Windows.Forms.Control.OnPaintBackground(PaintEventArgs pevent)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by Wagnerp** [comment]
That might be the latest commit that I did this morning on the `SeperatorController.cs`. The old code is still there, just commented out. I was trying to merge Phil Wright's latest fixes.
